apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft
spec:
  serviceName: raft
  replicas: 3
  selector:
    matchLabels:
      app: raft
  template:
    metadata:
      labels:
        app: raft
    spec:
      containers:
        - name: raft
          image: raft-project-webui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: raft-config
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PEERS
              value: "raft-0.raft,raft-1.raft,raft-2.raft"
